# permissions for end users to view nodejsapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodejsapplication-viewer-role
rules:
- apiGroups:
  - apps.mononoke.local
  resources:
  - nodejsapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.mononoke.local
  resources:
  - nodejsapplications/status
  verbs:
  - get
