# permissions for end users to view railsapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: railsapplication-viewer-role
rules:
- apiGroups:
  - apps.mononoke.local
  resources:
  - railsapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.mononoke.local
  resources:
  - railsapplications/status
  verbs:
  - get
