# permissions for end users to edit railsapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: railsapplication-editor-role
rules:
- apiGroups:
  - apps.mononoke.local
  resources:
  - railsapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.mononoke.local
  resources:
  - railsapplications/status
  verbs:
  - get
